// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcI-BOaQ-FsQb2U4uFabA_k2_-Km0QUM',
    appId: '1:282816287153:android:2c1974588b64e5c239ad90',
    messagingSenderId: '282816287153',
    projectId: 'nguyenhuytoan-firebase',
    storageBucket: 'nguyenhuytoan-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Iy-EX7i6ppJQ-kp33j8nWq-ycFg0nGI',
    appId: '1:282816287153:ios:bd3e3bae7a0b49ab39ad90',
    messagingSenderId: '282816287153',
    projectId: 'nguyenhuytoan-firebase',
    storageBucket: 'nguyenhuytoan-firebase.appspot.com',
    iosClientId: '282816287153-iu864kldi93k646odfk44hqg9gkid1cc.apps.googleusercontent.com',
    iosBundleId: 'vn.edu.ntu.huytoan.movieApp',
  );
}
